---
title: "Clase 2"
output: github_document
---

## Instalando la libreria 

```{r}
# install.packages("UsingR")
# install.packages("DataExplorer")

```

## Llamado de Librerias

```{r comment='', warning=FALSE }
library(lattice)
library(survival)
library(Formula)
library(ggplot2)
library(MASS) 
library(HistData)
library(Hmisc)
library(UsingR)
library(DataExplorer)
```

## Leyendo los datos

```{r comment=''}
data("nym.2002")
head(nym.2002)
```

## Estadistica Descriptiva

```{r comment=''}
mean(nym.2002$age)
hist(nym.2002)
```

## Customizando el Histograma

```{r}
hist(nym.2002$age, col="lightblue", main = "Edades Maraton", xlab = "Edades", freq = TRUE, labels = TRUE)
abline(v= mean(nym.2002$age), col='red')
```

## Libreria Data Explorer

### Reporte

```{r Data Explorer}
# create_report(nym.2002)

```

## Grafica de Barras

```{r Data Explorer 2, comment='',warning=FALSE}
plot_bar(nym.2002)
```

## Histogramas

```{r Data Explorer 3}
plot_histogram(nym.2002)
```


```{r Data Explorer 4}
plot_histogram(nym.2002$time)
```

## Grafica de Densidad

```{r Data Explorer 5}
plot_density(nym.2002)
```

## Box plot

```{r Data Explorer 6}
plot_boxplot(nym.2002, by = "age")
```


```{r Data Explorer 7}
plot_boxplot(nym.2002, by = "time")
```








